apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
        - name: app
          image: ghcr.io/roma-rgb-tech/devsecops-pipeline-demo:447f2dfc9cdf9b3533c434206f6f8a0587bd7209
          ports:
            - containerPort: 8000