apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
        - name: app
          image: ghcr.io/roma-rgb-tech/devsecops-pipeline-demo:5429a450f813cf5fe3d5db361fa7bf64651beee1
          ports:
            - containerPort: 8000