apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      containers:
        - name: app
          image: ghcr.io/roma-rgb-tech/devsecops-pipeline-demo:3f9394e01f00fe838e5f41206870c841fa3b0d07
          ports:
            - containerPort: 8000